### ISSUE TITLE
dlopen libaaudio.so failed

### ISSUE THREAD

**Issue by TheFool0415** [googlesamples/android-audio-high-performance#47] opened 2017-05-19 17:02 UTC
NDK version: 15.0.3996722 rc2

05-19 16:41:10.558 4755-4755/com.google.sample.com.google.sample.aaudio.play E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                               Process: com.google.sample.com.google.sample.aaudio.play, PID: 4755
                                                                                               java.lang.UnsatisfiedLinkError: dlopen failed: library "libaaudio.so" not found
                                                                                                   at java.lang.Runtime.loadLibrary0(Runtime.java:989)
                                                                                                   at java.lang.System.loadLibrary(System.java:1530)
                                                                                                   at com.google.sample.aaudio.play.MainActivity.<clinit>(MainActivity.java:92)
                                                                                                   at java.lang.Class.newInstance(Native Method)
                                                                                                   at android.app.Instrumentation.newActivity(Instrumentation.java:1078)
                                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2557)
                                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                                                   at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

and there is libaaudio.so in  ndk-bundle/platforms/android-26/${arch}/usr/lib/

**Comment by IgorGanapolsky** [comment] 2017-05-19 20:53
I am getting the same error in Android Studio 3.0:
> Process: com.google.sample.com.google.sample.aaudio.play, PID: 27578
                                                                                                 java.lang.UnsatisfiedLinkError: dlopen failed: library "libaaudio.so" not found

**Comment by IgorGanapolsky** [comment] 2017-05-19 21:03
The problem is in /hello-aaudio/hello-aaudio.gradle:
`'-DANDROID_PLATFORM=android-26'`

This means that the app cannot run on anything lower than Android O.  If you try to recompile with android-21, it won't compile.

**Comment by ggfan** [comment] 2017-05-19 21:29
Yeah, it must run on Android-O: AAudio is only enabled on Android - O; and this version of the audio sample must be run on Android-O-Beta1 (documentation call it Developer Preview version 2 ): because the callback mechanism only enabled in Android O Image in the second developer preview ( released on 05/17/2017 ) or later formal release

**Comment by IgorGanapolsky** [comment] 2017-05-19 21:31
@ggfan According to this talk at IO - https://www.youtube.com/watch?v=C0BPXZIvG-Q -
It should be possible to use aaudio_wrapper with dlsym to run on earlier platforms.  Is that true?

**Comment by ggfan** [comment] 2017-05-19 21:36
No, not the AAudio API, but the wrapper layer API ( it sits on top of openSL ES and AAudio ), I do not know what will be the final name for it ( I only knew the internal name, it will not help: its final name I did not know ).  that lib will be open source project, and be added into this repo when it is ready; it will NOT be inside android framework.  Phil's talk today does not have time to get more details on it; but his talk for Android Developer Preview 1 addressed that more.

I tried to have this Android-O requirement in the readme file for THIS sample:
  https://github.com/googlesamples/android-audio-high-performance/blob/master/aaudio/README.md
Will add code to check on target android device's API level, if less than 26, will gracefully fail.

**Comment by philburk** [comment] 2017-05-20 23:39
The reason to use dlopen() and dlsym() for linking AAudio is so that your app can be be loaded on new or old Android versions. If AAudio is not supported then dlopen() will return an error.  Then your app can decide to use OpenSL ES or fail gracefully.

If you did not use dlopen() then your app would not even load on old versions of Android.

**Comment by IgorGanapolsky** [comment] 2017-05-22 13:21
@philburk Wouldn't it be prudent to bake the dlsym into this sample, and target lower SDKs?

**Comment by philburk** [comment] 2017-05-22 15:00
The purpose of the sample code is only to demonstrate how AAudio works.  AAudio does not run on lower SDKs so the sample wouldn't run. 

Auto-switching between AAudio and OpenSL ES is a good thing but beyond the scope of this sample. I worry that if samples do too much then it obscures the essential information.

**Comment by IgorGanapolsky** [comment] 2017-05-22 15:08
Interesting.  I'd think the README should reflect these fine points, or get
rid of dlsym from the project.  Otherwise, developers will scratch their
heads and spend time figuring out what in the world is going on here :)

**Comment by ggfan** [comment] 2017-05-22 15:58
I am adding to check for API level and fail gracefully.

The sample right NOW is not using dlopen/dlsym(), the init code for that is inside third_party directory, that is more of personal -- developers to choose that way or traditional way ( it is more of convenience to my development ).  officially we kind of like to make the sample to be somewhat depends on new NDK ( with dlopen / dlsym in the sample, NDK-15 is not necessary, that could be a benefit )

**Comment by ggfan** [comment] 2017-05-22 16:47
https://github.com/googlesamples/android-audio-high-performance/pull/49  is merged: it should not load APK if target is NOT android-O.

**Closed by ggfan** 2017-05-22 16:47 UTC
